changelog:
  categories:
    - title: ğŸš€ Features
      labels:
        - "feature"
    - title: ğŸ› Bug Fixes
      labels:
        - "bug"
    - title: ğŸ”§ Maintenance
      labels:
        - "chore"
        - "refactor"
    - title: ğŸ“¦ Dependencies
      labels:
        - "dependencies"
    - title: Other Changes
      labels:
        - "*"
